### ISSUE TITLE
allow commenting out shortcuts

### ISSUE THREAD

**Issue by japhir** [LukeSmithxyz/shortcut-sync#2]
Hi Luke! Really enjoying your videos! 

I've just tried to implement the shortcut-sync scripts on my desktop, and was wondering if it would be possible to add comments to the configs and folders files, this would allow me to easily comment out some keyboard shortcuts and keep track of notes, like `# work directories` followed by a list of work-related directories.

Have a good one!

**Comment by LukeSmithxyz** [comment]
Hi Japhir, thanks!

While I'm now just writing the script in bash, I have added the feature to the bash script now. It should allow blank lines and comments with `#` either at the beginning of the line or elsewhere.

**Comment by japhir** [comment]
Great! The new bash-script looks very tidy! 👍
